import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { api, formValue, jsonBody } from '../api';
import type { ConversationDetail, ConversationListItem, Notify } from '../types';
import { Empty, formatDate } from './core';

type Template={id:string;meta_name:string;language_code:string;category:string|null;status:string;components_json:string};

export function WhatsAppPage({notify}:{notify:Notify}){
  const[items,setItems]=useState<ConversationListItem[]>([]);const[selectedId,setSelectedId]=useState<string|null>(null);const[detail,setDetail]=useState<ConversationDetail|null>(null);const[query,setQuery]=useState('');const[busy,setBusy]=useState(false);const[templates,setTemplates]=useState<Template[]>([]);const[fileRef]=[useRef<HTMLInputElement>(null)];
  const loadList=useCallback(()=>void api<ConversationListItem[]>(`/api/conversations?q=${encodeURIComponent(query)}`).then(rows=>{setItems(rows);setSelectedId(current=>current??rows[0]?.id??null);}).catch(error=>notify(error.message,'error')),[query,notify]);
  const loadDetail=useCallback((id:string)=>void api<ConversationDetail>(`/api/conversations/${id}`).then(value=>{setDetail(value);void api(`/api/conversations/${id}/read`,{method:'POST'}).catch(()=>undefined);}).catch(error=>notify(error.message,'error')),[notify]);
  useEffect(()=>{loadList();const timer=window.setInterval(loadList,5000);return()=>window.clearInterval(timer);},[loadList]);
  useEffect(()=>{if(selectedId){loadDetail(selectedId);const timer=window.setInterval(()=>loadDetail(selectedId),5000);return()=>window.clearInterval(timer);}setDetail(null);},[selectedId,loadDetail]);
  useEffect(()=>{void api<Template[]>('/api/templates').then(setTemplates).catch(()=>setTemplates([]));},[]);
  const selected=useMemo(()=>items.find(item=>item.id===selectedId)??null,[items,selectedId]);

  async function sendText(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedId)return;const form=event.currentTarget;const text=formValue(form,'message');if(!text)return;setBusy(true);try{await api('/api/messages/text',{method:'POST',...jsonBody({conversationId:selectedId,text,clientRequestId:crypto.randomUUID()})});form.reset();loadDetail(selectedId);loadList();notify('Mesaj gönderim kuyruğuna alındı.','success');}catch(error){notify(error instanceof Error?error.message:'Mesaj gönderilemedi.','error');}finally{setBusy(false);}}
  async function upload(file:File){if(!selectedId)return;setBusy(true);try{const data=new FormData();data.set('file',file);await api(`/api/conversations/${selectedId}/attachments`,{method:'POST',body:data});loadDetail(selectedId);notify('Dosya gönderim kuyruğuna alındı.','success');}catch(error){notify(error instanceof Error?error.message:'Dosya gönderilemedi.','error');}finally{setBusy(false);if(fileRef.current)fileRef.current.value='';}}
  async function changeMode(mode:string){if(!selectedId)return;try{await api(`/api/conversations/${selectedId}/ai-mode`,{method:'PUT',...jsonBody({mode,pausedUntil:null})});loadDetail(selectedId);notify('Konuşma AI modu güncellendi.','success');}catch(error){notify(error instanceof Error?error.message:'AI modu değiştirilemedi.','error');}}
  async function syncTemplates(){try{const result=await api<{count:number}>('/api/templates/sync',{method:'POST'});setTemplates(await api('/api/templates'));notify(`${result.count} şablon Meta’dan senkronize edildi.`,'success');}catch(error){notify(error instanceof Error?error.message:'Şablonlar alınamadı.','error');}}
  async function sendFirst(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;const variables=formValue(form,'variables').split('\n').map(value=>value.trim()).filter(Boolean);try{const result=await api<{conversationId:string}>('/api/messages/template',{method:'POST',...jsonBody({phone:formValue(form,'phone'),displayName:formValue(form,'name'),templateName:formValue(form,'template'),languageCode:formValue(form,'language'),variables})});form.reset();loadList();setSelectedId(result.conversationId);notify('İlk şablon mesajı kuyruğa alındı.','success');}catch(error){notify(error instanceof Error?error.message:'İlk mesaj gönderilemedi.','error');}}

  return <div className="wa-layout">
    <aside className="conversation-list panel"><div className="panel-heading compact"><div><h3>Konuşmalar</h3><p>{items.length} kayıt</p></div><input className="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Ara" /></div><div className="conversation-scroll">{items.map(item=><button key={item.id} className={`conversation-row ${selectedId===item.id?'active':''}`} onClick={()=>setSelectedId(item.id)}><div className="avatar">{(item.display_name||'?').slice(0,1).toUpperCase()}</div><div><strong>{item.display_name||item.phone_e164}</strong><span>{item.last_message||'Henüz mesaj yok'}</span><small>{formatDate(item.last_message_at)} · {item.ai_mode}</small></div>{item.unread_count>0&&<b>{item.unread_count}</b>}</button>)}</div>{!items.length&&<Empty text="Henüz WhatsApp konuşması yok." />}</aside>
    <section className="chat-panel panel">{detail?<><header className="chat-header"><div><h3>{detail.conversation.display_name}</h3><p>{detail.conversation.phone_e164} {detail.conversation.company_name?`· ${detail.conversation.company_name}`:''}</p></div><span className={`pill ${detail.conversation.human_takeover?'warn':'ready'}`}>{detail.conversation.human_takeover?'İnsan devraldı':`AI: ${detail.conversation.ai_mode}`}</span></header><div className="messages">{detail.messages.map(message=><article key={message.id} className={`bubble ${message.direction}`}><div>{message.original_name&&<a href={`/api/attachments/${String(message.attachment_id??'')}`}>📎 {message.original_name}</a>}{message.text_content&&<p>{message.text_content}</p>}</div><small>{message.sender_type}{message.ai_generated?' · AI':''} · {message.delivery_status} · {formatDate(message.created_at)}</small></article>)}</div><form className="composer" onSubmit={sendText}><textarea name="message" required placeholder="Müşteriye manuel mesaj yazın…" rows={3}/><div><input ref={fileRef} hidden type="file" accept="image/png,image/jpeg,image/webp,application/pdf,.docx,.xlsx,.csv,.txt" onChange={event=>{const file=event.target.files?.[0];if(file)void upload(file);}}/><button type="button" className="button secondary" onClick={()=>fileRef.current?.click()} disabled={busy}>PDF / Görsel / Belge Ekle</button><button className="button primary" disabled={busy}>{busy?'Gönderiliyor…':'Gönder'}</button></div></form></>:<Empty text="Bir konuşma seçin." />}</section>
    <aside className="customer-panel page-stack"><section className="panel"><h3>Müşteri ve AI</h3>{selected&&<div className="key-list"><p><span>İsim</span><strong>{selected.display_name}</strong></p><p><span>Telefon</span><strong>{selected.phone_e164}</strong></p><p><span>Firma</span><strong>{selected.company_name||'—'}</strong></p></div>}<label>Konuşma AI modu<select value={detail?.conversation.ai_mode??'off'} onChange={event=>void changeMode(event.target.value)}><option value="off">Kapalı</option><option value="suggestion">Yalnız öneri</option><option value="auto">Otomatik cevap</option><option value="business_hours">Mesai saatlerinde otomatik</option><option value="human">İnsan devraldı</option></select></label>{detail?.summary&&<div className="summary-box"><strong>Konuşma özeti</strong><p>{String((detail.summary as any).summary_text??'')}</p></div>}{detail?.lastDecision&&<div className="summary-box"><strong>Son AI kararı</strong><p>{String((detail.lastDecision as any).intent??'—')} · %{Math.round(Number((detail.lastDecision as any).confidence??0)*100)}</p></div>}</section><section className="panel"><div className="panel-heading compact"><div><h3>Yeni Müşteriye İlk Mesaj</h3><p>Yalnız Meta onaylı şablon.</p></div><button className="text-button" onClick={()=>void syncTemplates()}>Şablonları Yenile</button></div><form className="form-stack" onSubmit={sendFirst}><label>İsim<input name="name" required /></label><label>Telefon<input name="phone" required placeholder="+905…" /></label><label>Şablon<select name="template" required>{templates.filter(item=>item.status==='APPROVED').map(item=><option key={item.id} value={item.meta_name}>{item.meta_name}</option>)}</select></label><label>Dil kodu<input name="language" required defaultValue={templates.find(item=>item.status==='APPROVED')?.language_code||'tr'} /></label><label>Değişkenler<textarea name="variables" rows={3} placeholder="Her satıra bir değişken" /></label><button className="button primary">Şablon Mesajını Gönder</button></form></section></aside>
  </div>;
}
